language: java

install: "./.travis_install.sh"

script: mvn test -Dtest='fr.inria.astor.test.repair.evaluation.jKaliTest'

jdk:
  - oraclejdk7

notifications:
  email:
    - martin.monperrus@univ-lille1.fr
    - matias.sebastian.martinez@usi.ch


